etl:
  raw_data_file: "data/Placement_Data_Full_Class.csv"
  processed_path: "data"
  test_size: 0.2

train:
  processed_train: "data/train.csv"
  ensemble_model: "RandomForestClassifier"
  model_config: {n_estimators: 200}
  model_path: "model/model.pkl"

predict:
  model_path: "model/model.pkl"
  processed_test: "data/test.csv"
  predicted_file: "data/predict.csv"
  export_result: True
